---
- name: check if v2ray exists
  stat: 
    path: /usr/bin/v2ray/v2ray
  register: v2ray

- name: install v2ray
  become: true
  when: not v2ray.stat.exists
  command:  bash <(curl -L -s https://install.direct/go.sh)

- name: copy /etc/v2ray/config.json
  become: true
  copy: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: yes
  with_items:
    - { src: "config-client-office.json", dest: "/etc/v2ray/config-client-office.json" }
    - { src: "config-client-personal.json", dest: "/etc/v2ray/config-client-personal.json" }
    - { src: "config-server-personal.json", dest: "/etc/v2ray/config-server-personal.json" }

- name: Create symbolic link 
  become: true
  file:exit
    src: "/etc/v2ray/config-{{mode}}.json"
    dest: "/etc/v2ray/config.json"
    force: yes 
    state: link
 
- name: restart v2ray
  become: true
  systemd:
    name: v2ray
    enabled: yes
    state: restarted